03-03-21 møde testcase
ZealandNaestved/DAT20-UP-projekt pull request #120
Opened 2021-03-04 08:01 UTC by TheProphet4000

2021-03-04 08:02 UTC, TheProphet4000 commented
Pullrequest

2021-03-04 11:36 UTC, Madictian requested changes
Filen som tilføjes følger ikke Naming konventioner.
kunne filen evt. konverteres til Markdown eller spreadsheetet gøres til en statisk fil og ikke et online dokument som kan redigeres uden opsyn?

2021-03-05 08:02 UTC, VirtualZeth requested changes
Som Fredrik skriver :-) Lav det til en markdown fil i stedet med et navn der følger vores navngivnings konventioner

2021-03-05 08:22 UTC, Madictian requested changes
linje 1: dette er ikke et spreadsheet længere.
tusende -> tusinde(linje 13 og 14)
linje 12: klarificer mening, skal der gives en advarsel hvis man bruger komma?
linje 13: angiv mere tydeligt hvad der menes, rundes der op eller ned.
linje 14: hver 3. decimal fra højre tilføjer komme for at angive

2021-03-05 08:29 UTC, VirtualZeth requested changes
I test 5 bliver der advaret mod brugen af tegn som !/()#&", men lad os i stedet teste for både bogstaver og tegn på samme tid. (regex "\^[0-9]+$\g")

Når du giver et data input, brug tal i stedet således at det forventede resultat giver mere mening.

Jeg ville personligt dele testene op i deres egne test scenarier og beskrive hvert step i de scenarier. Se en reference her: https://github.com/ZealandNaestved/DAT20-UP-projekt/blob/main/05%20Test/Test02_Kundem%C3%B8de1.md
Det må du dog selv om du vil bruge samme metode :-)

2021-03-05 08:37 UTC, TheProphet4000 commented
Tænker jeg vil holde alle tests for sig.

2021-03-05 08:46 UTC, Madictian requested changes
har added inline comment på linje 1 og mangler der ikke punktum i test 4?

2021-03-05 08:48 UTC, VirtualZeth requested changes
Når du giver et data input, brug tal data i stedet således at det forventede resultat giver mere mening. Du behøver blot at give et eksempel. 4700 bliver til 4.7 når det omregnes til tusind. Dit forventede resultat vil være 4.7 og dit data input vil være 4700.

I test 5 bliver der advaret mod brugen af tegn som !/()#&", men lad os i stedet teste for både bogstaver og tegn på samme tid. (regex "^[0-9]+$\g") -> Vi vælger altså kun at acceptere tal. Det er en lille ændring, hvor vi i stedet forventer en fejlbesked som "Brug venligst ikke tegn eller bogstaver, kun tal accepteres" hvorefter at felterne der er fejl i bliver markeret.

2021-03-05 09:18 UTC, TheProphet4000 commented
@VirtualZeth  Jeg er lidt uenig med din ide, der jeg har lært noget andet på HTX. Der skulle vi lave så mange test som muligt, og kun teste for en ting (per test).
Men god pointe du har :D

2021-03-05 09:27 UTC, VirtualZeth commented
> @VirtualZeth Jeg er lidt uenig med din ide, der jeg har lært noget andet på HTX. Der skulle vi lave så mange test som muligt, og kun teste for en ting (per test).
> Men god pointe du har :D

Det er fint du er uening, så kan vi snakke om det ;) Vi er også enige om at der skal laves så mange tests som muligt. Hvis du nu skal skrive test 5 giver det også mening at teste for tegn, bogstaver, kombinationer af tegn og bogstaver, små bogstaver med store, tal med mellemrun, tal med bogstaver, tal med tegn, tal med bogstaver og tegn, men i selve programet vil det blive testet gennem en regex. Det vil sige at vi forventer en fejlmeddelese der beskriver alle de potentielle fejl brugeren kan lave. Fejlmeddelesen vil ikke kun være specifik for tegn. Den vil bede brugeren om kun at benytte tal.

2021-03-05 09:36 UTC, VirtualZeth requested changes
> @VirtualZeth Jeg er lidt uenig med din ide, der jeg har lært noget andet på HTX. Der skulle vi lave så mange test som muligt, og kun teste for en ting (per test).
> Men god pointe du har :D

Det er fint du er uening, så kan vi snakke om det ;) Vi er også enige om at der skal laves så mange tests som muligt. Hvis du nu skal skrive test 5 giver det også mening at teste for tegn, bogstaver, kombinationer af tegn og bogstaver, tomme felter, små bogstaver med store, tal med mellemrum, tal med bogstaver, tal med tegn, tal med bogstaver og tegn, men i selve programet vil det blive testet gennem en regex. Det vil sige at vi forventer en fejlmeddelese der beskriver alle de potentielle fejl brugeren kan lave. Fejlmeddelesen vil ikke kun være specifik for tegn. Den vil bede brugeren om kun at benytte tal.

Skal der ikke også være mere uddybende test trin hvor brugeren går fra start til slut og processen imellem bliver beskrevet?

2021-03-05 10:04 UTC, TheProphet4000 commented
@VirtualZeth  Har lavet en ny test, der tester for tegn, tal, og bogstaver. :D

2021-03-05 10:14 UTC, VirtualZeth approved these changes

2021-03-05 10:21 UTC, VirtualZeth commented on 05 Test/Test03_Testcases.md
> +  **1:** Skriv et tal, og se om det bliver vist. : Der bliver vist et tal : 47
Vær mere specifik, hvad tal bliver skrevet og hvor? Er det omsætning? Reklameomkostninger? Eller hvad input felt bliver testet.

2021-03-05 10:25 UTC, VirtualZeth commented on 05 Test/Test03_Testcases.md
> +  **5:** Skriv et tilfældigt tegn : Foventet advarsel om, tegnset ikke bruges : !/()#&"
Hvad advarsel forventes at blive sendt tilbage til brugeren?

Hvad bliver specifikt givet som input?

2021-03-05 10:26 UTC, VirtualZeth requested changes
Vær mere specifik, og gennemgå test trinene. Hvordan bliver brugerens input testet?

2021-03-05 10:49 UTC, VirtualZeth commented on 05 Test/Test03_Testcases.md
> +  **4:** Skriv et tal ind, i et hvilke som helst input, i tusinde : Der bliver automatisk sat et punktum ind, for hver tredje decimal : 4100
Hvis der bliver sat et punktum ind for hver tredje decimal, bliver det forventede output i det her tilfælde for 4100 = 4.100
Det skal skrives ned som forventet output.

2021-03-05 10:54 UTC, VirtualZeth commented on Testcase
> +https://docs.google.com/spreadsheets/d/1pVGyIdDySNni9vFSxZedMjm2QNyzsl-ecjFlQMVSOoQ/edit#gid=0
Lav det til en markdown fil. Tables er supported.
Lav et tables således:

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

2021-03-05 11:00 UTC, VirtualZeth commented on 05 Test/Test03_Testcases.md
> +  **4:** Skriv et tal ind, i et hvilke som helst input, i tusinde : Der bliver automatisk sat et punktum ind, for hver tredje decimal : 4.100
Nu har du skrevet 4.100 som dit data input. Men brugeren skriver ganske rigtigt 4100. Dit forventede test output er 4.100.
Hvis jeg var dig ville jeg stille det op som:
Test trin | data input (givet eksempel for input) | Forventet resultat
Ink. pass/fail

2021-03-05 11:00 UTC, VirtualZeth requested changes
Godt på vej, men lidt ændringer endnu :-)

2021-03-05 11:08 UTC, TheProphet4000 commented on 05 Test/Test03_Testcases.md
> +  **4:** Skriv et tal ind, i et hvilke som helst input, i tusinde : Der bliver automatisk sat et punktum ind, for hver tredje decimal : 4.100
Er det mulighed for du kan ændre det, er begyndt at tvivle på om det jeg laver er overhovedt rigtigt.

2021-03-05 11:11 UTC, VirtualZeth commented on 05 Test/Test03_Testcases.md
> +  **4:** Skriv et tal ind, i et hvilke som helst input, i tusinde : Der bliver automatisk sat et punktum ind, for hver tredje decimal : 4.100
Jeg kan lave et commit med mit bud :-)

2021-03-05 11:56 UTC, VirtualZeth commented
@TheProphet4000
Jeg har lavet ændringer, tag lige et kig og fortæl mig om du synes det er i orden :-)

2021-03-05 13:55 UTC, Madictian approved these changes

2021-03-05 13:55 UTC, merged