Udkast til faseplan iteration 1
ZealandNaestved/DAT20-UP-projekt pull request #147
Opened 2021-03-09 12:33 UTC by Madictian

Faseplan i Visio til gennemgang og feedback

2021-03-09 12:58 UTC, Bombohog reviewed
Jeg kan ikke some den eneste reviewer sige om det er godt nok, så jeg håber en anden person vil review også, og komme med deres mening.

2021-03-10 08:53 UTC, TheProphet4000 requested changes
Det er ingen synlige filer. Dette er hvad jeg kan se "Empty file. "

2021-03-10 08:56 UTC, simon-stentoft reviewed
Intet at se.

2021-03-10 08:59 UTC, Madictian commented
det er et visio dokument, så i bliver nød til at downloade det for at se det.

2021-03-10 09:00 UTC, TheProphet4000 commented
> 
> 
> det er et visio dokument, så i bliver nød til at downloade det for at se det.

Men der er intet at downloade, ingen filer eller noget.

2021-03-10 15:05 UTC, TheProphet4000 approved these changes

2021-03-10 15:12 UTC, LostButStillImproving approved these changes

2021-03-10 15:12 UTC, merged