SD til UseCase1
ZealandNaestved/DAT20-UP-projekt pull request #201
Opened 2021-03-11 12:54 UTC by MMadsen99

Skal reviewes af 3 personer før den merges

2021-03-11 13:53 UTC, Mewmewww requested changes
https://imgur.com/a/f7HOybw 

Som nævnt i discord-samtalen, så er fælles-meningen at if-sætningen [omsætning != known] skal trækkes over else statement - da inputOmsætning er "known".

2021-03-11 13:56 UTC, MMadsen99 commented
Filen er blevet opdateret med den nye ændring omkring alt framet

2021-03-11 13:58 UTC, Mewmewww approved these changes
Jeg godkender denne SD efter deres rettelse - ønsker endvidere 2 reviewers som kan bekræfte/benægte denne SDs status

2021-03-11 16:29 UTC, Dani025a reviewed
Jeg kan se i har taget 0 med i mængde og salgpris, men tænker hvis en af dem er 0 og den anden er f.eks. 100, så vil det give 0. Ved ikke om det skal ses som en fejl eller om man bare kan fortsætte. Bare et forslag.

2021-03-12 07:56 UTC, TheProphet4000 reviewed
Kigger på det

2021-03-12 08:19 UTC, Dani025a commented
> Vil mene at " >= 0 " burde være >= 1 der man ikke kan gange med 0, uden det hele bliver 0.
> Mit bud er, at den skal mælde fejl når man prøver at gange med null/0.

2021-03-12 08:21 UTC, TheProphet4000 commented
> Problemet med der er at hvis den er >=1 så kan salgsprisen ikke være f.eks. 0,5
Hvad så med >=0,01 eller er det bare fjollet?

2021-03-12 08:23 UTC, Dani025a commented
> > Problemet med der er at hvis den er >=1 så kan salgsprisen ikke være f.eks. 0,5
> 
> Hvad så med >=0,01 eller er det bare fjollet?

Jeg tænker det skal bare være > 0

2021-03-12 08:27 UTC, TheProphet4000 commented
> Jeg tænker det skal bare være > 0

okay, fair nok. Jeg kan rigtigt ikke se andre problemer.

2021-03-12 08:40 UTC, TheProphet4000 requested changes
Det giver ikke mening at have >= 0 der man ikke vil sælge noget gratis

2021-03-12 09:19 UTC, TheProphet4000 approved these changes

2021-03-12 09:23 UTC, Dani025a approved these changes

2021-03-12 09:36 UTC, merged