SD til UseCase2
ZealandNaestved/DAT20-UP-projekt pull request #203
Opened 2021-03-11 13:25 UTC by ChilasDipo

2021-03-11 14:20 UTC, Mewmewww requested changes
I den første lange regneudtryk - så skal i benytte &&-konnotationen for AND.
Personligt mener jeg, at istedet for at skrive "negativt tal" - så hellere skriv at vareforbruget eller omsætningen skal være >= 0 - det samme gælder for numerisk værdi (eksempelvis kunne det opskrives således == numeric)

Det ser også ud til, at SD'en også kunne benytte en ekstra if-sætningen, der konstaterer at bruttofortjenesten ikke er kendt - da vi har 2 muligheder (inputBruttofortjeneste eller calculateBruttofortjeneste). I har kun lavet for calculateBruttofortjeneste.

Yderligere, så ville det gavne os hvis vi havde 2 else-statements, en else statement for inputBruttofortjeneste (hvis de har en allerede-oplyst en), og selvfølgelig en else-statement for en exception hvis inputtet giver en error.

https://imgur.com/a/bZ4Jtia

2021-03-12 10:27 UTC, Mewmewww requested changes
Næsten perfekt - lige ovenover inputBruttofortjeneste, så mangles der en [else]. Når det er rettet, så skulle det være yderst acceptabelt.

2021-03-12 13:20 UTC, Mewmewww approved these changes
Smukt fra mit vedkommende :)

2021-03-15 08:11 UTC, TheProphet4000 approved these changes

2021-03-15 08:12 UTC, TheProphet4000 commented
Har kigget det igennem, og det ser smukt ud.

2021-03-15 08:12 UTC, merged