Added main screen fxml file
ZealandNaestved/DAT20-UP-projekt pull request #208
Opened 2021-03-11 14:38 UTC by AsHuOvSo

tilføjet main screen fxml fil. Labels, textfields, og buttons har alle fået et unikt id

2021-03-11 15:00 UTC, AsHuOvSo commented
![scshmainScreen](https://user-images.githubusercontent.com/70743121/110806996-e38d9c00-8282-11eb-84f5-088bd153b8a8.PNG)

2021-03-11 15:49 UTC, LostButStillImproving requested changes
Flot arbejde, so far, men der er nogle få mangler i forhold til mockup:

1. 1.000 kr knappen skal være en ToggleButton, ikke Button. Med en Label ved siden af.
2. "tilføj kommentarer til resultatopgørelse" skal være en knap, med tekst og image. Lige nu er det en knap med tekst.
3. Det samme gælder for alle knapper som har et image view siden af . 

Jeg er ikke helt sikker på hvorvidt, at de rettelser er nødvendige at få med i prototypen, så det kan vi eventuelt lige få på plads.

Ellers godt arbejde!

2021-03-11 16:16 UTC, Dani025a commented
Kommentar skal kunne tiljøjes for hver enkelt nøgleord, ved ikke om det skal være muligt at man trykker på den knap du har lavet også kan vælge nøgleordet, eller om der skal være kommentarknap for hvert nøgleord

2021-03-11 17:42 UTC, AsHuOvSo commented
"1.000 kr" knappen er en toggle button. Det er den type jeg satte ind i SceneBuilder.
Jeg tænker at der er nogen der skal lave et par assets til bl.a. knapper og ikon.
Det med kommentarerne er jeg ikke helt sikker på. Fulgte det der var på mockup'en, men jeg er ikke helt sikker på hvordan vi skal gøre, medmindre der skal tilføjes et + ved hver post hvor man kan tilføje kommentarer.

2021-03-11 18:01 UTC, LostButStillImproving commented
ord


> "1.000 kr" knappen er en toggle button. Det er den type jeg satte ind i SceneBuilder.
> Jeg tænker at der er nogen der skal lave et par assets til bl.a. knapper og ikon.
> Det med kommentarerne er jeg ikke helt sikker på. Fulgte det der var på mockup'en, men jeg er ikke helt sikker på hvordan vi skal gøre, medmindre der skal tilføjes et + ved hver post hvor man kan tilføje kommentarer.

Min fejl, det er allerede en ToggleButton. Perfekt!

mht. assets så er det selvfølgelig ikke noget du skal ordne i forbindelse ved det her issue, jeg efterbeder bare at funktionaliteten er således at et billede kan tilføjes til en knap når vi når så langt.

2021-03-11 18:42 UTC, Dani025a commented
> ord
> 
> > "1.000 kr" knappen er en toggle button. Det er den type jeg satte ind i SceneBuilder.
> > Jeg tænker at der er nogen der skal lave et par assets til bl.a. knapper og ikon.
> > Det med kommentarerne er jeg ikke helt sikker på. Fulgte det der var på mockup'en, men jeg er ikke helt sikker på hvordan vi skal gøre, medmindre der skal tilføjes et + ved hver post hvor man kan tilføje kommentarer.
> 
> Min fejl, det er allerede en ToggleButton. Perfekt!
> 
> mht. assets så er det selvfølgelig ikke noget du skal ordne i forbindelse ved det her issue, jeg efterbeder bare at funktionaliteten er således at et billede kan tilføjes til en knap når vi når så langt.
> 
> mht. kommentarerne, så er jeg heller ikke helt sikker på det punkt. Men det ved @Dani025a måske.

Jeg kan ikke huske hvordan de ville have kommentarerne, det kan være @sasaje @Madictian @MBRzealand  kan huske det

2021-03-11 18:48 UTC, Dani025a commented
De her ting blev ikke tilføjet til mockup, men det var feedback vi fik fra kunde mødet i onsdags 
https://github.com/ZealandNaestved/DAT20-UP-projekt/blob/main/08%20Project%20Management/PM07_KM_NotesFromCustomerMeeting3.md

2021-03-12 15:15 UTC, LostButStillImproving approved these changes

2021-03-12 15:16 UTC, Hjordrup approved these changes
Synes det ser godt ud som en prototype, hvor design kan på senere.

2021-03-12 15:16 UTC, LostButStillImproving commented
@AsHuOvSo

Vi merger branchen her, og laver et nyt issue hvor de få manglende krav kræves rettet :)

2021-03-12 15:16 UTC, merged