Add files via upload
ZealandNaestved/DAT20-UP-projekt pull request #210
Opened 2021-03-11 21:45 UTC by usamahjavaid

2021-03-12 10:42 UTC, Mewmewww requested changes
Et par ting som skal rettes.
Alt (Alternatives) er if-sætninger, så du er nødt til at lave statements der enten bekræftes/benægtes.
1: Den overordnede if-sætning - der skal du skrive de krav der skal enten gælde/benægtes. Med andre ord, så er det de krav der gælder for at man kan udregne markedsføringsbidraget.
Måden jeg ville skrive det op på: [Bruttofortjeneste >= 0 && Bruttofortjeneste == numeric &&  salgsfremmendeOmkostninger >= 0 && salgsfremmendeOmkostninger == numeric || Markedsføringsbidrag >= 0 && Markedsføringsbidrag == numeric]
2: Her ville jeg lave 2 ting - først en ekstra alt der har kravet (Markedsføringsbidrag != known), da der godt kan være scenarier hvor vi har fået en markedsføringsbidrag oplyst. 
2.5: Inde i den, så ville jeg lave en **loop** hvor du udregner markedsføringsbidraget
3: Her ville jeg rykke exceptionen ned til den næste kasse, og erstatte den med en [else] samt noget vi kalder inputMarkedsføringsbidrag. Dens pil skal føres helt til den sidste klasse, hvorved den tilsvarende returnerer markedsføringsbidraget til controlleren. 
4: TIl sidst skal du bare beholde den exception som før - den skal bare rykkes ned til den fjerde boks. Husk at statements og krav som [else] eller den forrige-nævnte lange regneudtryk skal centreres, ikke ud på venstre side.

Skriv lige/ring lige på discord (Deniz), hvis du er usikker
https://imgur.com/a/atJjddK

2021-03-15 08:54 UTC, Bombohog approved these changes
Jeg syntes den er god, men hvis Deniz vil have at den skal ændres efter at have set ændringer, så må vi jo tage et gik på det igen.

2021-03-15 11:09 UTC, Mewmewww requested changes
Usamah - jeg har set dig en besked af hvordan jeg synes det skulle se ud. (scyllabae)

2021-03-16 09:04 UTC, Bombohog approved these changes
Det ser godt ud.

2021-03-16 09:15 UTC, simon-stentoft approved these changes
(y)

2021-03-16 09:29 UTC, ChilasDipo approved these changes

2021-03-16 09:29 UTC, merged