DM 06 til rettelse
ZealandNaestved/DAT20-UP-projekt pull request #242
Opened 2021-03-12 12:05 UTC by usamahjavaid

2021-03-12 14:38 UTC, sasaje requested changes
1. Bruger bør ændres til HØK-studerende. 

2. Vi forstår ikke helt begreb lommeregner?, ift. mockup er der ikke nogle "lommeregner"/feature pop-up tilknyttet dette felt. Men hvis der menes selve beregningsfunktionaliteten, så kunne Lommeregner ændres evt. til "renteomkostninger - resultatFoerRenter".

3. implements mellem "afgrænsning" og "Lommeregner" dækker for 1 (multiplicity). Ligeledes mellem "Resultatopgørelses og "View". - Justér labels. 

4. Ensret begyndelsesbogstav i labels. 

5. Der er noget galt med label "indeholder" mellem "ResultatFørRenter" og "Resultatopgørelse". 

6. Benyt ikke æ,ø,å i navngivning. 

7. Fra ResultatFørRenter til Resultatopgørelse skal der sættes et pilehoved på pilen, der går fra Resultatopgørelse til ResultatFørRenter. 

8. Fra View til Resultatopgørelse skal der sættes et pilehoved på pilen, der går fra View til Resultatopgørelse. 

9. Resultat skal flyttes fra "Lommeregner" og placeres et sted efter ResultatFørRenter. 

Co-author: @KRL1991 
Co-author: @MMadsen99

2021-03-15 08:40 UTC, sasaje requested changes
Lidt endnu: 

1. implements rettes til implementerer
2. Definere rettes til nutid - definererer.  
3. Afgræningens multiplicitet: hvis DM går ud fra at der skal være mindst én fejl i inputformatet, så er det rigtig fint med 1,..*. Ellers ville vi sige, at der skal stå 0,...*, da der ikke nødvendigvis er mindst én fejl?

Co-authors: @KRL1991 
Co-authors: @MMadsen99

2021-03-16 07:32 UTC, KRL1991 approved these changes
Jeg synes det ser godt ud nu :) -  afventer lige de to andres mening

2021-03-16 08:34 UTC, sasaje requested changes
1. implementerer står over 1-tallet. 
2. både implementerer og definerer står med småt begyndelsesbogstav, mens de resterende står med stort. 

Co-authored-by: MMadsen99 <71014091+MMadsen99@users.noreply.github.com>
Co-authored-by: KRL <70881764+KRL1991@users.noreply.github.com>

2021-03-16 08:45 UTC, MMadsen99 approved these changes
Det ser fint ud nu

2021-03-16 08:48 UTC, sasaje approved these changes

2021-03-16 08:48 UTC, merged