SD for OC 04 til rettelse
ZealandNaestved/DAT20-UP-projekt pull request #246
Opened 2021-03-12 13:05 UTC by usamahjavaid

2021-03-15 13:22 UTC, Bombohog requested changes
Der mangler at blive skrevet hvilken type der bliver passed
såsom ":int" eller ":double"

2021-03-15 13:43 UTC, Bombohog approved these changes
Yep, det ser godt ud.

2021-03-16 09:55 UTC, Madictian requested changes
Jeg ville mene at det ikke er controlleren som kaster exceptions men der hvor metode kaldet forekommer

2021-03-16 10:07 UTC, Madictian approved these changes

2021-03-16 10:07 UTC, merged