Beskrivelseafbeta
ZealandNaestved/DAT20-UP-projekt pull request #266
Opened 2021-03-15 12:04 UTC by adler92

2021-03-15 12:48 UTC, sasaje commented on 06 Deployment/DP02_DescriptionOfBetaRelease.md
> +Navnet på programmet for denne beta release er Hoekcel. Den henvender sig til studerende på Handelsøkonomuddannelsen på Erhvervsakademi Sjælland, der ønsker at kunne sætte et resultatbudget/resultato
1. Handelsøkonomuddannelsen skal stå med lille begyndelsesbogstav.  
2. Skolen hedder vidst Zealand nu, i stedet for Erhvervsakademi Sjælland :)

2021-03-15 12:49 UTC, sasaje commented on 06 Deployment/DP02_DescriptionOfBetaRelease.md
> +Formålet er at give brugeren et overblik over hele budget og udviklingen af firmaets nøgletal over en periode. Produktet vil assistere brugeren i, at indsætte de korrekte værdier og samtidig give dem
"budget" kunne erstattes med opgørelsen (evt. resultatopgørelse)

2021-03-15 12:50 UTC, sasaje commented on 06 Deployment/DP02_DescriptionOfBetaRelease.md
> +Formålet er at give brugeren et overblik over hele budget og udviklingen af firmaets nøgletal over en periode. Produktet vil assistere brugeren i, at indsætte de korrekte værdier og samtidig give dem
Skal man evt. udspecificerer de forskellige nøgletal? Altså hvilke nøgletal, der er tale om?

2021-03-15 12:50 UTC, sasaje requested changes
Se kommentarer :)

2021-03-15 13:06 UTC, Mewmewww requested changes

2021-03-15 13:06 UTC, Mewmewww commented on 06 Deployment/DP03_UserManualForBetaRelease.md
> +   * Værdierne må ikke være negative eller med bogstaver
bruttofortjeneste, markedsførisnbsbidrag, indtjeningsbidrag, renteførresultat - disse 4 værdier må godt være negativ. De er værdier som vi manuelt kan inputte, så hvis en af disse værdier bliver negative - så crasher programmet.

2021-03-15 13:42 UTC, Ravnen707 commented
Vi har kigget på jeres forslag til ændringer samt jeres rettelser til diverse punkter. Hvis ikke til for meget besvær vil vi gerne bede om endnu en gennemgang.

2021-03-15 14:08 UTC, Mewmewww approved these changes
I forhold til min rettelse, så er det helt fint :)

2021-03-16 08:14 UTC, Bombohog requested changes
Tag lige og kig på dette.

2021-03-16 08:14 UTC, Bombohog commented on 06 Deployment/DP03_UserManualForBetaRelease.md
> +    * på ‘Tilføj ny kapacitetsomkostninger’ og udfyldt felterne
Du skal ikke klikke på pludset, man kan også bare skrive et tal ind, så du skal gøre lidt alla som i gjorde lidt længere oppe, med hvis den er kendt så skriver man den ind, men hvis den ikke er, så skal/kan man klikke (+).

2021-03-16 08:14 UTC, Bombohog commented on 06 Deployment/DP03_UserManualForBetaRelease.md
> +4. Hvis omsætningen ikke er kendt på forhånd - Tryk på + ikonet.
Jeg så længere nede at du skrev det i 1 punkt, men her har du skrevet det i 2.

2021-03-16 08:17 UTC, Bombohog requested changes
Her er en mere dum ting.

2021-03-16 08:17 UTC, Bombohog commented on 06 Deployment/DP03_UserManualForBetaRelease.md
> +**Problem**: Bugs (Fejl der ikke skyldes brugeren)
Mener i "Der ikke skyldes af brugeren"? så i mangler "af".

2021-03-16 08:28 UTC, Bombohog approved these changes
i approve.

2021-03-16 08:30 UTC, merged