Tilføjet Alpha Brugervejledning
ZealandNaestved/DAT20-UP-projekt pull request #267
Opened 2021-03-15 13:15 UTC by MBRzealand

Co-authored-by: Mewmewww <11328730+Mewmewww@users.noreply.github.com>
Co-authored-by: sasaje <70880973+sasaje@users.noreply.github.com>
Co-authored-by: gusajer <70881859+gusajer@users.noreply.github.com>
Co-authored-by: Madictian <70747015+Madictian@users.noreply.github.com>

Closes #171

2021-03-15 13:22 UTC, KRL1991 commented
Måske er det os der ikke ved hvordan man gør - men billeder bliver ikke vist i markdown

Co-author @MMadsen99

2021-03-15 13:22 UTC, KRL1991 reviewed
Måske er det os der ikke ved hvordan man gør - men billeder bliver ikke vist i markdown

Co-author @MMadsen99

2021-03-15 14:11 UTC, Ravnen707 requested changes
Har pointerede nogle små stavefejl samt kommaer punkter.

Men ellers syntes jeg at alt ser fint ud :)

2021-03-15 14:11 UTC, Ravnen707 commented on 06 Deployment/DP03_BrugermanualForAlpha.md
> +  *Her ses vores automatiserede ui, siden at programmet er lavet til at hjælpe med at udregne et resultat budget og
ui skal skrives med stort "UI"

2021-03-15 14:11 UTC, Ravnen707 commented on 06 Deployment/DP03_BrugermanualForAlpha.md
> +*Det første man ligger mærke til er at der står nogle tomme felter med en "titel" og et felt man kan angive numre i. I dette billede kan vi se at vi har 3 felter som arbejder sammen, en til omsætning
Kommaer: "Ligger mærke til, er at" / "kan vi se, at vi"

2021-03-15 14:11 UTC, Ravnen707 commented on 06 Deployment/DP03_BrugermanualForAlpha.md
> +*I det næste billede kan vi se at en bruger har angivet omsætningen og vareforbruget og så har systemet udregnet og vist/præsenteret bruttofortjenesten. Dette forløb sker flere gange, men med andre f
Kommaer: "kan vi se, at en bruger"

2021-03-16 07:59 UTC, Ravnen707 commented
Alt er ok for min side af.

2021-03-16 08:00 UTC, Ravnen707 approved these changes

2021-03-16 08:02 UTC, Bombohog approved these changes
Den ser godt ud.

2021-03-16 08:02 UTC, KRL1991 approved these changes
Looks good

2021-03-16 08:03 UTC, merged