Create Test10_Usecase04-Actual.md
ZealandNaestved/DAT20-UP-projekt pull request #314
Opened 2021-03-17 12:49 UTC by Ravnen707

2021-03-17 13:15 UTC, MBRzealand requested changes

2021-03-17 13:15 UTC, MBRzealand commented on 05 Test/Test10_Usecase04-Actual.md
> +Systemet oplyser at kontante omkostninger skal beskrives med tal. og beder om et nyt indput.
Der skal stå "input"

2021-03-17 13:17 UTC, MBRzealand requested changes

2021-03-17 13:17 UTC, MBRzealand commented on 05 Test/Test10_Usecase04-Actual.md
> +Systemet oplyser at kontante omkostninger ikke må være negativ. og beder om et nyt tal.
ikke punktum før "og"

2021-03-17 13:17 UTC, MBRzealand commented on 05 Test/Test10_Usecase04-Actual.md
> +Systemet oplyser at kontante omkostninger skal beskrives med tal. og beder om et nyt indput.
heller ikke punktum før "og"

2021-03-18 07:57 UTC, Ravnen707 commented
Rettet punktum fejl og stavefejl i forhold til MBRzealand rettelser

2021-03-18 08:31 UTC, Bombohog reviewed
Ud fra at der ikke var tidligere test scenarier så ser det godt ud, men der kunne måske mangle nogle få nogle, såsom hvis brugeren ikke skriver noget ind, eller lign.

2021-03-18 10:50 UTC, Bombohog approved these changes
Det ser godt ud.

2021-03-18 11:07 UTC, gusajer approved these changes
efter jeg har læst det i gennem og kan se, at de andre requests er blevet lavet kan jeg godt approve.

2021-03-18 11:07 UTC, merged